### Site info:

title : 장 혁의 이야기 공간
tagline: "데이터와 이야기를 통해 세상을 바라보고 관찰하는 공학도"
author: Andrew Hyouk JANG
email: hyouk.a.jang@gmail.com
description: "The blog of Andrew JANG"
keywords: "Data, Informatics, Mathematics, Physics, R, Python, Virtual Reality, Hardware, Hyouk JANG, Engineer, Entrepreneur"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hyoukjang.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
github_username:  hyoukjang
disqus_shortname: hyoukjang
favicon:     "/images/favicon.ico"
google_analytics_key: UA-98488675-1 # put YOUR key here to enable tracking! (blank to disable)
#aboutme: Hi, this is Lijia Yu.  # these are shown on aboutme-sidebar.
#aboutme_photo: https://i.imgur.com/15BT1.jpg # your photo.


### Site setting:
ShowContactInfo: "False" 
default_column: "one" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

#Blogroll:
#    - name: Yihui Xie's Blog       
#      href: http://yihui.name      
#      title: author of knitr, I think he is the Small Forward of R world now.

### Build settings
markdown: kramdown
kramdown:
        input: GFM
        syntax_highlighter: rouge
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
exclude: [Rakefile]
